/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerProfile = IDL.Record({
  'coinBalance' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'lifetimeCoins' : IDL.Nat,
  'purchasedItems' : IDL.Vec(IDL.Text),
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCoins' : IDL.Func([IDL.Nat], [], []),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
      ['query'],
    ),
  'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
  'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
  'getShopCatalog' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'purchaseItem' : IDL.Func([IDL.Text], [], []),
  'submitScore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerProfile = IDL.Record({
    'coinBalance' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'lifetimeCoins' : IDL.Nat,
    'purchasedItems' : IDL.Vec(IDL.Text),
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCoins' : IDL.Func([IDL.Nat], [], []),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
        ['query'],
      ),
    'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
    'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
    'getShopCatalog' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'purchaseItem' : IDL.Func([IDL.Text], [], []),
    'submitScore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };